repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-executables-have-shebangs
    -   id: debug-statements

-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.0-a5
    hooks:
    -   id: pylint
        args: [
                "--max-line-length=100",
                "--disable=C0103,C0111,R0901,R0902,R0903,R0904,R0911,R0912,R0913,R0914"
        ]
        language_version: python3
        exclude: ^docs|tests

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: [
                "--max-line-length=100"
        ]
        language_version: python3
        exclude: ^docs|tests

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [
                "--line-length", "100"
        ]
        language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: [
                "--profile", "black", "--filter-files"
        ]
        language_version: python3

-   repo: local
    hooks:
    -   id: pytest
        always_run: true
        entry: python3 -m pytest
        language: system
        name: pytest
        pass_filenames: false
